version: '3.8'

services:
  html-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dj3dw-html-editor
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
